# Generated by Django 5.1.1 on 2024-09-30 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='MenuItem',
        ),
        migrations.RenameModel(
            old_name='Purchases',
            new_name='Purchase',
        ),
        migrations.RenameModel(
            old_name='RecipeRequirements',
            new_name='RecipeRequirement',
        ),
    ]
