# Generated by Django 5.1.1 on 2024-09-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_reciperequirement_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciperequirement',
            old_name='price',
            new_name='ingredient_price',
        ),
    ]
