# Generated by Django 5.1.1 on 2024-10-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_alter_reciperequirement_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperequirement',
            name='unit',
            field=models.CharField(default='units', max_length=50),
        ),
    ]
