# Generated by Django 5.1.1 on 2024-10-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_reciperequirement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='ingredient',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='item',
            field=models.CharField(max_length=50),
        ),
    ]
