# Generated by Django 5.1.1 on 2024-10-15 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequirement',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_requirements', to='Inventory.ingredient'),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_requirements', to='Inventory.menuitem'),
        ),
    ]
