# Generated by Django 5.1.1 on 2024-10-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0016_ingredient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='date_purchased',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
