# Generated by Django 5.1.1 on 2024-10-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0019_ingredient_category_ingredient_date_purchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
