# Generated by Django 5.1.1 on 2024-10-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0020_alter_ingredient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperequirement',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
