# Generated by Django 5.1.1 on 2024-10-16 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0028_purchase_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_quantity', to='Inventory.reciperequirement'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='unit_price',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_unit_price', to='Inventory.reciperequirement'),
        ),
    ]
