# Generated by Django 5.1.1 on 2024-10-20 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0034_ingredient_user_menuitem_user_purchase_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reciperequirement',
            name='user',
        ),
    ]
